### ISSUE TITLE
[P1] Featured jobs click is broken

### ISSUE THREAD

**Issue by joelcloralt** [Instajob/instajobwebapp#2]
Clicking on a featured job doesn't do anything.
I was logged out when I did this.

**Comment by avidyut1** [comment]
on home page right? what should we do?

**Comment by codelion** [comment]
@avidyut1 it should do what it does everywhere else on the site. It needs to show the details view on the modal in the same way as we already have in the JobsNearMe, SavedJobs, MatchedJobs, and,  Map view.

CC: @joelcloralt

**Comment by avidyut1** [comment]
done
