### ISSUE TITLE
[P1] Mismatched alignment of job cards

### ISSUE THREAD

**Issue by codelion** [Instajob/instajobwebapp#7]
All job cards should appear of the same size. If there is more text it needs to be shown only in details view that comes up when we click on the job. Currently they are misaligned if the responsibility section is a bit long as shown below - 

![screen shot 2015-08-22 at 9 24 32 am](https://cloud.githubusercontent.com/assets/603317/9421881/bbcd34a4-48af-11e5-9fec-056e12506ec0.png)

**Comment by avidyut1** [comment]
done
